// pdf-lib is ~400 kB unminified. It's imported dynamically so that the
// wizard's earlier steps stay fast — the library only lands when the
// caseworker actually clicks "Download PDF".

import { PROGRAM_NAMES } from './programs'

const FIELD_LABELS = {
  client_name: 'Applicant name',
  date_of_birth: 'Date of birth',
  address: 'Street address',
  city: 'City',
  state: 'State',
  zip_code: 'ZIP',
  phone_number: 'Phone',
  email: 'Email',
  household_size: 'Household size',
  monthly_income: 'Monthly income',
  monthly_rent: 'Monthly rent',
  utility_cost: 'Monthly utility cost',
}

const ORDER = [
  'client_name', 'date_of_birth', 'address', 'city', 'state', 'zip_code',
  'phone_number', 'email', 'household_size', 'monthly_income',
  'monthly_rent', 'utility_cost',
]

function formatValue(key, value) {
  if (value == null || value === '') return '(not provided)'
  if (key === 'monthly_income' || key === 'monthly_rent' || key === 'utility_cost') {
    const num = Number(value)
    if (Number.isNaN(num)) return String(value)
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(num)
  }
  return String(value)
}

export async function renderPacketPdf({ programId, profile, actionCard }) {
  const { PDFDocument, StandardFonts, rgb } = await import('pdf-lib')
  const doc = await PDFDocument.create()
  const page = doc.addPage([612, 792]) // US Letter
  const { width, height } = page.getSize()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)

  const margin = 48
  let y = height - margin

  // Title
  const programName = PROGRAM_NAMES[programId] || programId
  const title = `${programName} Application`
  page.drawText(title, { x: margin, y, size: 18, font: bold, color: rgb(0.11, 0.23, 0.52) })
  y -= 22

  // Subtitle
  page.drawText('Auto-prepared from CaseBridge intake', {
    x: margin, y, size: 9, font, color: rgb(0.45, 0.45, 0.45),
  })
  y -= 8
  page.drawLine({
    start: { x: margin, y },
    end: { x: width - margin, y },
    thickness: 1,
    color: rgb(0.85, 0.85, 0.85),
  })
  y -= 24

  // Fields
  page.drawText('Applicant information', { x: margin, y, size: 12, font: bold, color: rgb(0.1, 0.1, 0.1) })
  y -= 18

  for (const key of ORDER) {
    const label = FIELD_LABELS[key]
    const value = formatValue(key, profile[key])
    page.drawText(label, { x: margin, y, size: 10, font: bold, color: rgb(0.3, 0.3, 0.3) })
    page.drawText(value, { x: margin + 160, y, size: 10, font, color: rgb(0.1, 0.1, 0.1) })
    y -= 16
  }

  // Household members
  if (profile.household_members?.length > 0) {
    y -= 8
    page.drawText('Household members', { x: margin, y, size: 12, font: bold, color: rgb(0.1, 0.1, 0.1) })
    y -= 18
    for (const m of profile.household_members) {
      const parts = [m.name]
      if (m.age != null) parts.push(`age ${m.age}`)
      if (m.relationship) parts.push(m.relationship)
      page.drawText(`- ${parts.join(' / ')}`, { x: margin + 12, y, size: 10, font, color: rgb(0.1, 0.1, 0.1) })
      y -= 14
    }
  }

  // Required documents
  if (actionCard?.docs_needed?.length > 0) {
    y -= 12
    page.drawText('Documents to bring to submission', { x: margin, y, size: 12, font: bold, color: rgb(0.1, 0.1, 0.1) })
    y -= 18
    for (const doc of actionCard.docs_needed) {
      page.drawText(`[ ] ${doc}`, { x: margin + 12, y, size: 10, font, color: rgb(0.1, 0.1, 0.1) })
      y -= 14
    }
  }

  // Submission info
  if (actionCard?.submission_url || actionCard?.deadline) {
    y -= 12
    page.drawText('Submit to', { x: margin, y, size: 12, font: bold, color: rgb(0.1, 0.1, 0.1) })
    y -= 18
    if (actionCard.submission_url) {
      page.drawText(actionCard.submission_url, { x: margin + 12, y, size: 9, font, color: rgb(0.11, 0.23, 0.52) })
      y -= 14
    }
    if (actionCard.deadline) {
      page.drawText(`Deadline: ${actionCard.deadline}`, {
        x: margin + 12, y, size: 9, font, color: rgb(0.35, 0.35, 0.35),
      })
      y -= 14
    }
  }

  // Footer
  page.drawText('Generated by CaseBridge | Review before submission', {
    x: margin,
    y: margin - 20,
    size: 8,
    font,
    color: rgb(0.6, 0.6, 0.6),
  })

  const bytes = await doc.save()
  return new Blob([bytes], { type: 'application/pdf' })
}

export function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
