import { useState, useRef } from 'react'
import { useCaseSession } from '../context/CaseContext'

const SEVERITY_COLORS = {
  RED: 'text-red-600',
  AMBER: 'text-amber-600',
}

export default function ExportSummary() {
  const { caseSession, timeline } = useCaseSession()
  const [isOpen, setIsOpen] = useState(false)
  const [copied, setCopied] = useState(false)
  const contentRef = useRef(null)

  if (timeline.length === 0) return null

  const today = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  const clientName = caseSession.clientName || 'Client'
  const formEvents = timeline.filter((e) => e.type.startsWith('form-'))

  // Calculate time saved
  let totalMinutes = 0
  for (const event of timeline) {
    if (event.type === 'case-note') totalMinutes += 45
    else if (event.type === 'resources') totalMinutes += 20
    else if (event.type.startsWith('form-')) totalMinutes += 15
  }

  const handleCopy = async () => {
    if (!contentRef.current) return
    try {
      await navigator.clipboard.writeText(contentRef.current.innerText)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // fallback
    }
  }

  const handlePrint = () => {
    const printWindow = window.open('', '_blank')
    if (!printWindow || !contentRef.current) return
    printWindow.document.write(`
      <html>
        <head>
          <title>Session Report - ${clientName}</title>
          <style>
            body { font-family: 'DM Sans', system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; }
            h1 { font-size: 20px; border-bottom: 2px solid #2563eb; padding-bottom: 8px; }
            h2 { font-size: 16px; color: #374151; margin-top: 24px; }
            table { width: 100%; border-collapse: collapse; margin: 12px 0; }
            th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
            th { background: #f9fafb; font-weight: 600; }
            .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 11px; font-weight: 600; }
            .red { background: #fef2f2; color: #dc2626; }
            .amber { background: #fffbeb; color: #d97706; }
            .meta { color: #6b7280; font-size: 12px; }
            pre { white-space: pre-wrap; font-family: inherit; font-size: 13px; line-height: 1.6; background: #f9fafb; padding: 16px; border-radius: 8px; }
            .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; }
          </style>
        </head>
        <body>${contentRef.current.innerHTML}<div class="footer">Generated by CaseBridge | CPP AI Hackathon 2026</div></body>
      </html>
    `)
    printWindow.document.close()
    printWindow.print()
  }

  if (!isOpen) {
    return (
      <button
        onClick={() => setIsOpen(true)}
        className="fixed bottom-6 right-6 z-30 flex items-center gap-2 px-4 py-2.5 bg-brand-600 text-white rounded-full shadow-lg hover:bg-brand-700 transition-colors cursor-pointer text-sm font-medium"
      >
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5" />
        </svg>
        Export Session
      </button>
    )
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/40" onClick={() => setIsOpen(false)} />

      {/* Modal */}
      <div className="relative bg-white rounded-xl shadow-2xl max-w-3xl w-full max-h-[85vh] flex flex-col">
        {/* Header bar */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200 flex-shrink-0">
          <h2 className="text-lg font-bold text-gray-900">Session Report</h2>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-gray-600 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors cursor-pointer"
            >
              {copied ? (
                <>
                  <svg className="w-3.5 h-3.5 text-emerald-600" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                  </svg>
                  Copied!
                </>
              ) : (
                <>
                  <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M15.666 3.888A2.25 2.25 0 0013.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 01-.75.75H9.75a.75.75 0 01-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 01-2.25 2.25H6.75A2.25 2.25 0 014.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 011.927-.184" />
                  </svg>
                  Copy
                </>
              )}
            </button>
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-gray-600 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors cursor-pointer"
            >
              <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231c-.662 0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0 0021 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055 0 00-1.913-.247M6.34 18H5.25A2.25 2.25 0 013 15.75V9.456c0-1.081.768-2.015 1.837-2.175a48.041 48.041 0 011.913-.247m10.5 0a48.536 48.536 0 00-10.5 0m10.5 0V3.375c0-.621-.504-1.125-1.125-1.125h-8.25c-.621 0-1.125.504-1.125 1.125v3.659M18 10.5h.008v.008H18V10.5zm-3 0h.008v.008H15V10.5z" />
              </svg>
              Print
            </button>
            <button
              onClick={() => setIsOpen(false)}
              className="text-gray-400 hover:text-gray-600 cursor-pointer p-1 ml-2"
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-5" ref={contentRef}>
          <h1 className="text-xl font-bold text-gray-900 pb-2 border-b-2 border-brand-600 mb-4">
            Session Report — {clientName} — {today}
          </h1>

          {/* Session Metadata */}
          <div className="grid grid-cols-3 gap-4 mb-6 text-sm">
            <div>
              <span className="text-xs text-gray-500 uppercase tracking-wide">Steps Completed</span>
              <div className="font-semibold text-gray-900">{timeline.length}</div>
            </div>
            <div>
              <span className="text-xs text-gray-500 uppercase tracking-wide">Time Saved</span>
              <div className="font-semibold text-emerald-700">~{totalMinutes} min</div>
            </div>
            <div>
              <span className="text-xs text-gray-500 uppercase tracking-wide">Date</span>
              <div className="font-semibold text-gray-900">{new Date().toLocaleDateString('en-US')}</div>
            </div>
          </div>

          {/* Case Note */}
          {caseSession.generatedNote && (
            <div className="mb-6">
              <h2 className="text-sm font-semibold text-gray-700 uppercase tracking-wide mb-2">
                Case Note ({caseSession.format} Format)
              </h2>
              <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed bg-gray-50 p-4 rounded-lg border border-gray-200 max-h-60 overflow-y-auto">
                {caseSession.generatedNote}
              </pre>
            </div>
          )}

          {/* Risk Assessment */}
          {caseSession.riskFlags.length > 0 && (
            <div className="mb-6">
              <h2 className="text-sm font-semibold text-gray-700 uppercase tracking-wide mb-2">
                Risk Assessment
              </h2>
              <table className="w-full text-sm border border-gray-200 rounded-lg overflow-hidden">
                <thead>
                  <tr className="bg-gray-50">
                    <th className="text-left px-3 py-2 font-medium text-gray-600">Risk Factor</th>
                    <th className="text-left px-3 py-2 font-medium text-gray-600">Severity</th>
                    <th className="text-left px-3 py-2 font-medium text-gray-600">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {caseSession.riskFlags.map((flag, i) => (
                    <tr key={i}>
                      <td className="px-3 py-2 text-gray-900">{flag.keyword}</td>
                      <td className="px-3 py-2">
                        <span className={`inline-block px-2 py-0.5 text-xs font-semibold rounded-full ${
                          flag.severity === 'RED' ? 'bg-red-50 text-red-600' : 'bg-amber-50 text-amber-600'
                        }`}>
                          {flag.severity}
                        </span>
                      </td>
                      <td className="px-3 py-2 text-gray-600">{flag.recommendation}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Resources */}
          {caseSession.matchedResources && caseSession.matchedResources.length > 0 && (
            <div className="mb-6">
              <h2 className="text-sm font-semibold text-gray-700 uppercase tracking-wide mb-2">
                Resources Identified
              </h2>
              <table className="w-full text-sm border border-gray-200 rounded-lg overflow-hidden">
                <thead>
                  <tr className="bg-gray-50">
                    <th className="text-left px-3 py-2 font-medium text-gray-600">Resource</th>
                    <th className="text-left px-3 py-2 font-medium text-gray-600">Type</th>
                    <th className="text-left px-3 py-2 font-medium text-gray-600">Match</th>
                    <th className="text-left px-3 py-2 font-medium text-gray-600">Contact</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {caseSession.matchedResources.map((r, i) => (
                    <tr key={i}>
                      <td className="px-3 py-2 text-gray-900 font-medium">{r.name}</td>
                      <td className="px-3 py-2 text-gray-600">{r.type}</td>
                      <td className="px-3 py-2 text-gray-600">{r.matchScore}%</td>
                      <td className="px-3 py-2 text-gray-600">{r.phone}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Forms Prepared */}
          {formEvents.length > 0 && (
            <div className="mb-6">
              <h2 className="text-sm font-semibold text-gray-700 uppercase tracking-wide mb-2">
                Forms Prepared
              </h2>
              <ul className="space-y-2">
                {formEvents.map((e, i) => (
                  <li key={i} className="flex items-center gap-2 text-sm">
                    <span className="w-2 h-2 bg-emerald-500 rounded-full" />
                    <span className="text-gray-900">{e.label}</span>
                    {e.detail && <span className="text-gray-500">— {e.detail}</span>}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
